item { 
	name:'CAREFUL'
	id:1
}
item { 
	name:'DHAVE'
	id:2
}
item { 
	name:'FINE'
	id:3
}
item { 
	name:'HATE'
	id:4
}
item { 
	name:'HAVE'
	id:5
}
item { 
	name:'HOME'
	id:6
}
item { 
	name:'ILY'
	id:7
}
item { 
	name:'IRRITATED'
	id:8
}
item { 
	name:'RIGHT'
	id:9
}
item { 
	name:'WAIT'
	id:10
}
item { 
	name:'WHY'
	id:11
}
